<?

$skinList[] = array('name'=>"tt01",'str_skin_name'=>'온라인교무실스킨1');
$skinList[] = array('name'=>"tt02",'str_skin_name'=>'온라인교무실스킨2');
$skinList[] = array('name'=>"gt01",'str_skin_name'=>'동아리스킨1');
$skinList[] = array('name'=>"gt02",'str_skin_name'=>'동아리스킨2');
$skinList[] = array('name'=>"gt03",'str_skin_name'=>'동아리스킨3');
$skinList[] = array('name'=>"ct01",'str_skin_name'=>'학급홈페이지스킨1');
$skinList[] = array('name'=>"ct02",'str_skin_name'=>'학급홈페이지스킨2');
$skinList[] = array('name'=>"ct03",'str_skin_name'=>'학급홈페이지스킨3');

?>